'*.{ts,tsx,js}':
  - 'eslint --cache --cache-location ./node_modules/.cache/.eslintcache --fix'
  - 'prettier --log-level log --cache --write'
'*.{json,yml,scss}': 'prettier --log-level log --cache --write'